### ISSUE TITLE
feature request: whitelist / blacklist for ddl commands

### ISSUE THREAD

**Issue by mzwettler2** [pgaudit/set_user#61]
Hi,

It would be cool if set_user would also provide a whitelist / blacklist for ddl commands.

Someone might allow users to become temporarily more privileged (eg. superuser) while still prohibit some specific actions (eg. create database).

Cheers, Markus

**Comment by mpalmi** [comment]
Thanks for submitting the feature request @mzwettler2. I can certainly look into this. To clarify, the usecase would be to block superuser from doing specific DDL after escalation?

**Comment by mzwettler2** [comment]
Yes, indeed. 
There might be several usecases:
- allowing someone to become superuser while still blocking specific DDL
- allowing someone to become another user (eg. application owner) while still blocking specific DDLs

**Comment by mpalmi** [comment]
After careful consideration, I think this feature belongs in another extension (though, I'm certainly willing to be convinced otherwise!)

The underlying implementation seems simple enough:
- Insert `superuser()` checks in various DDL code paths (either via an `object_access_hook` or `ProcessUtility_hook`).
- Add the allowlist/denylist check using PG_CMDTAG names to these blocks.

There are some usability implications: 
1) Potentially very long allowlists.
2) There's likely a non-negligible performance hit from this feature. This would have to be accounted for.
3) How do I inform a user of valid SQL syntaxes? Long lists could be error-prone and hard to facilitate fixing.
4) Postgres version compatibility adds another layer of complexity.

I'm sure I'm missing plenty of other potential pitfalls.

This feature seems to me like it could/should be its own extension, as it's essentially a SQL firewall and likely very complex.

I'll continue to think about a way to simplify this or only support a subset of the desired functionality, but at the moment, I'm not sure. 

I would also be willing to entertain a patch submission if you can think of a novel solution to this problem

**Comment by mpalmi** [comment]
I'm going to go ahead and close out this issue since there hasn't been any recent activity. Feel free to re-open. Thanks!
